// docs/src/components/primitives/checkbox.tsx
import { createCheckbox } from "../../../../packages/solid-apg/src";

export function Checkbox() {
	const { elements, props } = createCheckbox();

	const { root, input } = elements;

	return (
		<>
			<button use:root {...props}>
				<input use:input />
			</button>

			<button>Odemknout</button>
		</>
	);
}

// apps/solid-start-example/src/components/Checkbox.tsx
"use client";

import { createSignal, onMount } from "solid-js";
import { createCheckbox } from "../../../../packages/solid-apg/src";

export default function Checkbox() {
	// const {
	// 	elements: { root },
	// 	props
	// } = createCheckbox();

	const { elements, props } = createCheckbox({
		disabled: true
	});

	const { root, input } = elements;

	return (
		<form>
			<button use:root {...props}>
				<input use:input />
			</button>

			<button>Odemknout</button>
		</form>
	);
}
